// ПОЛНАЯ база данных оружия Battlefield 6
const weaponsDatabase = [
    // ========== ШТУРМОВЫЕ ВИНТОВКИ (8 штук) ==========
    {
        id: 1,
        name: "M433",
        class: "assault",
        rank: 1,
        fireRate: "high",
        damage: 28,
        accuracy: 65,
        control: 70,
        range: 62,
        mobility: 75,
        distance: "medium",
        description: "Базовая штурмовая винтовка с отличной управляемостью"
    },
    {
        id: 2,
        name: "B36A4",
        class: "assault",
        rank: 2,
        fireRate: "medium",
        damage: 32,
        accuracy: 68,
        control: 68,
        range: 68,
        mobility: 72,
        distance: "medium",
        description: "Сбалансированная винтовка с улучшенной точностью"
    },
    {
        id: 3,
        name: "SOR-556 Mk2",
        class: "assault",
        rank: 3,
        fireRate: "high",
        damage: 26,
        accuracy: 63,
        control: 75,
        range: 60,
        mobility: 78,
        distance: "medium",
        description: "Компактная штурмовая винтовка для агрессивного стиля"
    },
    {
        id: 4,
        name: "AK4D",
        class: "assault",
        rank: 2,
        fireRate: "medium",
        damage: 34,
        accuracy: 66,
        control: 65,
        range: 70,
        mobility: 70,
        distance: "medium",
        description: "Мощная винтовка в стиле АК с высокой отдачей"
    },
    {
        id: 5,
        name: "TR-7",
        class: "assault",
        rank: 4,
        fireRate: "very high",
        damage: 24,
        accuracy: 60,
        control: 72,
        range: 55,
        mobility: 80,
        distance: "medium",
        description: "Высокоскоростная тактическая винтовка"
    },
    {
        id: 6,
        name: "KORD 6P67",
        class: "assault",
        rank: 3,
        fireRate: "medium",
        damage: 33,
        accuracy: 70,
        control: 67,
        range: 72,
        mobility: 68,
        distance: "medium",
        description: "Тяжелая штурмовая винтовка с высокой проникающей способностью"
    },
    {
        id: 7,
        name: "NVO-228E",
        class: "assault",
        rank: 5,
        fireRate: "burst",
        damage: 36,
        accuracy: 75,
        control: 70,
        range: 75,
        mobility: 65,
        distance: "medium",
        description: "Инновационная винтовка с режимом стрельбы очередями"
    },
    {
        id: 8,
        name: "L85A3",
        class: "assault",
        rank: 4,
        fireRate: "medium",
        damage: 31,
        accuracy: 72,
        control: 69,
        range: 74,
        mobility: 69,
        distance: "medium",
        description: "Британская штурмовая винтовка с отличной эргономикой"
    },

    // ========== КАРАБИНЫ (8 штук) ==========
    {
        id: 9,
        name: "M4A1",
        class: "carbine",
        rank: 1,
        fireRate: "high",
        damage: 26,
        accuracy: 64,
        control: 74,
        range: 58,
        mobility: 82,
        distance: "medium",
        description: "Классический карабин с высокой универсальностью"
    },
    {
        id: 10,
        name: "M277",
        class: "carbine",
        rank: 2,
        fireRate: "medium",
        damage: 30,
        accuracy: 67,
        control: 70,
        range: 65,
        mobility: 78,
        distance: "medium",
        description: "Компактная винтовка для ближнего и среднего боя"
    },
    {
        id: 11,
        name: "AK-205",
        class: "carbine",
        rank: 3,
        fireRate: "medium",
        damage: 32,
        accuracy: 65,
        control: 68,
        range: 67,
        mobility: 76,
        distance: "medium",
        description: "Карабин на базе АК с улучшенной мобильностью"
    },
    {
        id: 12,
        name: "M417 A2",
        class: "carbine",
        rank: 4,
        fireRate: "medium",
        damage: 35,
        accuracy: 69,
        control: 66,
        range: 72,
        mobility: 72,
        distance: "medium",
        description: "Точный карабин для марксманских задач"
    },
    {
        id: 13,
        name: "GRT-BC",
        class: "carbine",
        rank: 3,
        fireRate: "high",
        damage: 27,
        accuracy: 63,
        control: 73,
        range: 60,
        mobility: 80,
        distance: "medium",
        description: "Быстрый карабин с низкой отдачей"
    },
    {
        id: 14,
        name: "QBZ-192",
        class: "carbine",
        rank: 2,
        fireRate: "medium",
        damage: 31,
        accuracy: 66,
        control: 71,
        range: 68,
        mobility: 77,
        distance: "medium",
        description: "Китайский карабин с балансом мощности и контроля"
    },
    {
        id: 15,
        name: "SG 553R",
        class: "carbine",
        rank: 5,
        fireRate: "high",
        damage: 29,
        accuracy: 68,
        control: 72,
        range: 70,
        mobility: 74,
        distance: "medium",
        description: "Швейцарский карабин премиум-класса"
    },
    {
        id: 16,
        name: "SOR-300SC",
        class: "carbine",
        rank: 6,
        fireRate: "medium",
        damage: 33,
        accuracy: 71,
        control: 69,
        range: 75,
        mobility: 70,
        distance: "medium",
        description: "Тактический карабин из Season 1: Red Ops",
        season: "Season 1"
    },

    // ========== ПИСТОЛЕТЫ-ПУЛЕМЕТЫ (8 штук) ==========
    {
        id: 17,
        name: "SGX",
        class: "smg",
        rank: 1,
        fireRate: "very high",
        damage: 20,
        accuracy: 58,
        control: 78,
        range: 35,
        mobility: 90,
        distance: "close",
        description: "Высокоскоростной ПП для ближнего боя"
    },
    {
        id: 18,
        name: "PW5A3",
        class: "smg",
        rank: 2,
        fireRate: "high",
        damage: 22,
        accuracy: 60,
        control: 76,
        range: 40,
        mobility: 88,
        distance: "close",
        description: "Компактный ПП с хорошей стабильностью"
    },
    {
        id: 19,
        name: "PW7A2",
        class: "smg",
        rank: 3,
        fireRate: "high",
        damage: 23,
        accuracy: 61,
        control: 77,
        range: 42,
        mobility: 87,
        distance: "close",
        description: "Улучшенная версия PW5A3 с лучшей эргономикой"
    },
    {
        id: 20,
        name: "UMG-40",
        class: "smg",
        rank: 2,
        fireRate: "medium",
        damage: 25,
        accuracy: 63,
        control: 74,
        range: 45,
        mobility: 85,
        distance: "close",
        description: "Мощный ПП с увеличенным уроном"
    },
    {
        id: 21,
        name: "USG-90",
        class: "smg",
        rank: 4,
        fireRate: "very high",
        damage: 19,
        accuracy: 57,
        control: 80,
        range: 32,
        mobility: 92,
        distance: "close",
        description: "Экстремальная скорострельность для CQB"
    },
    {
        id: 22,
        name: "KV9",
        class: "smg",
        rank: 3,
        fireRate: "medium",
        damage: 26,
        accuracy: 64,
        control: 73,
        range: 48,
        mobility: 83,
        distance: "close",
        description: "Тяжелый ПП с хорошей пробивной способностью"
    },
    {
        id: 23,
        name: "SCW-10",
        class: "smg",
        rank: 5,
        fireRate: "high",
        damage: 24,
        accuracy: 62,
        control: 75,
        range: 44,
        mobility: 86,
        distance: "close",
        description: "Тактический ПП с интегрированным глушителем"
    },
    {
        id: 24,
        name: "SL9",
        class: "smg",
        rank: 4,
        fireRate: "burst",
        damage: 28,
        accuracy: 66,
        control: 72,
        range: 50,
        mobility: 82,
        distance: "close",
        description: "ПП с режимом очереди для точных выстрелов"
    },

    // ========== РУЧНЫЕ ПУЛЕМЕТЫ (8 штук) ==========
    {
        id: 25,
        name: "L110",
        class: "lmg",
        rank: 1,
        fireRate: "high",
        damage: 30,
        accuracy: 62,
        control: 64,
        range: 65,
        mobility: 60,
        distance: "medium",
        description: "Легкий пулемет с хорошей мобильностью"
    },
    {
        id: 26,
        name: "DRS-IAR",
        class: "lmg",
        rank: 2,
        fireRate: "medium",
        damage: 33,
        accuracy: 65,
        control: 62,
        range: 68,
        mobility: 58,
        distance: "medium",
        description: "Пулемет пехотинца с увеличенной точностью"
    },
    {
        id: 27,
        name: "M/60",
        class: "lmg",
        rank: 3,
        fireRate: "medium",
        damage: 35,
        accuracy: 63,
        control: 60,
        range: 72,
        mobility: 52,
        distance: "medium",
        description: "Классический пулемет с высокой огневой мощью"
    },
    {
        id: 28,
        name: "RPKM",
        class: "lmg",
        rank: 4,
        fireRate: "medium",
        damage: 34,
        accuracy: 64,
        control: 61,
        range: 75,
        mobility: 55,
        distance: "medium",
        description: "Модернизированный РПК с улучшенными характеристиками"
    },
    {
        id: 29,
        name: "M123K",
        class: "lmg",
        rank: 3,
        fireRate: "low",
        damage: 38,
        accuracy: 67,
        control: 58,
        range: 78,
        mobility: 50,
        distance: "long",
        description: "Тяжелый пулемет для подавления противника"
    },
    {
        id: 30,
        name: "M250",
        class: "lmg",
        rank: 5,
        fireRate: "high",
        damage: 31,
        accuracy: 66,
        control: 63,
        range: 70,
        mobility: 57,
        distance: "medium",
        description: "Современный пулемет с ленточным питанием"
    },
    {
        id: 31,
        name: "KTS100 MK8",
        class: "lmg",
        rank: 4,
        fireRate: "very high",
        damage: 29,
        accuracy: 61,
        control: 65,
        range: 62,
        mobility: 62,
        distance: "medium",
        description: "Высокоскоростной пулемет ближнего боя"
    },
    {
        id: 32,
        name: "M240L",
        class: "lmg",
        rank: 6,
        fireRate: "medium",
        damage: 36,
        accuracy: 65,
        control: 59,
        range: 80,
        mobility: 48,
        distance: "long",
        description: "Мощный пулемет общего назначения"
    },

    // ========== МАРКСМАНСКИЕ ВИНТОВКИ (4 штуки) ==========
    {
        id: 33,
        name: "M39 EMR",
        class: "dmr",
        rank: 2,
        fireRate: "semi",
        damage: 55,
        accuracy: 75,
        control: 68,
        range: 80,
        mobility: 62,
        distance: "medium",
        description: "Точная полуавтоматическая винтовка"
    },
    {
        id: 34,
        name: "LMR27",
        class: "dmr",
        rank: 3,
        fireRate: "semi",
        damage: 58,
        accuracy: 77,
        control: 66,
        range: 82,
        mobility: 60,
        distance: "medium",
        description: "Легкая марксманская винтовка"
    },
    {
        id: 35,
        name: "SVK-8.6",
        class: "dmr",
        rank: 4,
        fireRate: "semi",
        damage: 65,
        accuracy: 79,
        control: 64,
        range: 85,
        mobility: 58,
        distance: "long",
        description: "Мощная DMR под патрон 8.6мм"
    },
    {
        id: 36,
        name: "SVDM",
        class: "dmr",
        rank: 5,
        fireRate: "semi",
        damage: 62,
        accuracy: 78,
        control: 65,
        range: 84,
        mobility: 59,
        distance: "long",
        description: "Модернизированная версия классической СВД"
    },

    // ========== СНАЙПЕРСКИЕ ВИНТОВКИ (4 штуки) ==========
    {
        id: 37,
        name: "M2010 ESR",
        class: "sniper",
        rank: 3,
        fireRate: "bolt",
        damage: 90,
        accuracy: 85,
        control: 70,
        range: 95,
        mobility: 48,
        distance: "long",
        description: "Современная снайперская винтовка"
    },
    {
        id: 38,
        name: "SV-98",
        class: "sniper",
        rank: 2,
        fireRate: "bolt",
        damage: 88,
        accuracy: 84,
        control: 72,
        range: 93,
        mobility: 50,
        distance: "long",
        description: "Российская снайперская винтовка"
    },
    {
        id: 39,
        name: "PSR",
        class: "sniper",
        rank: 4,
        fireRate: "bolt",
        damage: 92,
        accuracy: 86,
        control: 68,
        range: 96,
        mobility: 46,
        distance: "long",
        description: "Высокоточная снайперская система"
    },
    {
        id: 40,
        name: "Mini Scout",
        class: "sniper",
        rank: 6,
        fireRate: "bolt",
        damage: 75,
        accuracy: 82,
        control: 75,
        range: 85,
        mobility: 60,
        distance: "medium",
        description: "Компактная снайперская винтовка из Season 1",
        season: "Season 1"
    },

    // ========== ДРОБОВИКИ (4 штуки) ==========
    {
        id: 41,
        name: "M87A1",
        class: "shotgun",
        rank: 1,
        fireRate: "pump",
        damage: 85,
        accuracy: 50,
        control: 60,
        range: 25,
        mobility: 70,
        distance: "close",
        description: "Надежный помповый дробовик"
    },
    {
        id: 42,
        name: "M1014",
        class: "shotgun",
        rank: 2,
        fireRate: "semi",
        damage: 70,
        accuracy: 52,
        control: 65,
        range: 30,
        mobility: 72,
        distance: "close",
        description: "Полуавтоматический дробовик"
    },
    {
        id: 43,
        name: "18.5KS-K",
        class: "shotgun",
        rank: 3,
        fireRate: "pump",
        damage: 90,
        accuracy: 48,
        control: 58,
        range: 28,
        mobility: 68,
        distance: "close",
        description: "Мощный тактический дробовик"
    },
    {
        id: 44,
        name: "DB-12",
        class: "shotgun",
        rank: 6,
        fireRate: "double",
        damage: 95,
        accuracy: 45,
        control: 55,
        range: 20,
        mobility: 65,
        distance: "close",
        description: "Двуствольный дробовик из Season 1: Cold Rage",
        season: "Season 1"
    },

    // ========== ПИСТОЛЕТЫ (6 штук) ==========
    {
        id: 45,
        name: "P18",
        class: "pistol",
        rank: 1,
        fireRate: "semi",
        damage: 35,
        accuracy: 60,
        control: 75,
        range: 30,
        mobility: 95,
        distance: "close",
        description: "Стандартный пистолет"
    },
    {
        id: 46,
        name: "ES 5.7",
        class: "pistol",
        rank: 2,
        fireRate: "semi",
        damage: 30,
        accuracy: 65,
        control: 78,
        range: 35,
        mobility: 94,
        distance: "close",
        description: "Высокоскоростной пистолет"
    },
    {
        id: 47,
        name: "M45A1",
        class: "pistol",
        rank: 3,
        fireRate: "semi",
        damage: 45,
        accuracy: 58,
        control: 70,
        range: 40,
        mobility: 92,
        distance: "close",
        description: "Мощный пистолет калибра .45"
    },
    {
        id: 48,
        name: "M44",
        class: "pistol",
        rank: 4,
        fireRate: "revolver",
        damage: 75,
        accuracy: 62,
        control: 65,
        range: 50,
        mobility: 90,
        distance: "close",
        description: "Мощный револьвер"
    },
    {
        id: 49,
        name: "GGH-22",
        class: "pistol",
        rank: 6,
        fireRate: "semi",
        damage: 40,
        accuracy: 63,
        control: 72,
        range: 38,
        mobility: 93,
        distance: "close",
        description: "Тактический пистолет из Season 1",
        season: "Season 1"
    },
    {
        id: 50,
        name: "M357 Trait",
        class: "pistol",
        rank: 6,
        fireRate: "revolver",
        damage: 80,
        accuracy: 60,
        control: 63,
        range: 55,
        mobility: 88,
        distance: "close",
        description: "Эксклюзивный револьвер из Season 1",
        season: "Season 1"
    },

    // ========== БОЕВЫЕ ПОДБОРКИ (2 штуки) ==========
    {
        id: 51,
        name: "MP-RMG",
        class: "battlepickup",
        rank: 7,
        fireRate: "very high",
        damage: 40,
        accuracy: 55,
        control: 50,
        range: 60,
        mobility: 40,
        distance: "medium",
        description: "Ручной многоцелевой гранатомет",
        special: "Battle Pickup"
    },
    {
        id: 52,
        name: "Rorsch Mk-2 SMRW",
        class: "battlepickup",
        rank: 7,
        fireRate: "railgun",
        damage: 100,
        accuracy: 90,
        control: 40,
        range: 99,
        mobility: 30,
        distance: "long",
        description: "Экспериментальный рельсотрон",
        special: "Battle Pickup"
    },

    // ========== БЛИЖНИЙ БОЙ (4 штуки) ==========
    {
        id: 53,
        name: "KBR Mark II",
        class: "melee",
        rank: 1,
        fireRate: "melee",
        damage: 50,
        accuracy: 100,
        control: 85,
        range: 2,
        mobility: 100,
        distance: "close",
        description: "Стандартный тактический нож"
    },
    {
        id: 54,
        name: "14lb Sledgehammer",
        class: "melee",
        rank: 3,
        fireRate: "melee",
        damage: 85,
        accuracy: 70,
        control: 60,
        range: 3,
        mobility: 80,
        distance: "close",
        description: "Тяжелый кувалда для ближнего боя"
    },
    {
        id: 55,
        name: "Bighorn HK-16",
        class: "melee",
        rank: 4,
        fireRate: "melee",
        damage: 65,
        accuracy: 90,
        control: 75,
        range: 2,
        mobility: 95,
        distance: "close",
        description: "Тактический топорик"
    },
    {
        id: 56,
        name: "Nomad CX-12",
        class: "melee",
        rank: 6,
        fireRate: "melee",
        damage: 70,
        accuracy: 85,
        control: 80,
        range: 2,
        mobility: 90,
        distance: "close",
        description: "Эксклюзивный нож из Season 1: Wild Ops",
        season: "Season 1"
    }
];

// Классы оружия
const weaponClasses = {
    assault: "Штурмовая винтовка",
    carbine: "Карабин",
    smg: "Пистолет-пулемет",
    lmg: "Ручной пулемет",
    dmr: "Марксманская винтовка",
    sniper: "Снайперская винтовка",
    shotgun: "Дробовик",
    pistol: "Пистолет",
    battlepickup: "Боевая подборка",
    melee: "Оружие ближнего боя"
};

// Цвета классов
const classColors = {
    assault: "#3b82f6",
    carbine: "#0ea5e9",
    smg: "#10b981",
    lmg: "#f59e0b",
    dmr: "#8b5cf6",
    sniper: "#ef4444",
    shotgun: "#ec4899",
    pistol: "#84cc16",
    battlepickup: "#f97316",
    melee: "#64748b"
};

console.log("✅ ПОЛНАЯ база данных оружия загружена! Всего: " + weaponsDatabase.length + " оружий");